### ISSUE TITLE
Runtime question

### ISSUE THREAD

**Issue by Dominic101** [jike5/LATITUDE#1]
Can you provide an estimate of how long it took to train the pose regressor? Also, how long does it take the pose regressor to provide an initial pose guess and how long does the pose optimization phase take to produce the optimized pose? Thanks!

**Comment by jike5** [comment]
> Can you provide an estimate of how long it took to train the pose regressor? Also, how long does it take the pose regressor to provide an initial pose guess and how long does the pose optimization phase take to produce the optimized pose? Thanks!

Training the pose regressor takes about an hour, inference takes about 1s, and for the pose optimization phase it takes a little longer, about a few minutes, but this also depends on your device and the scale of the scene
